ProyectoFinal/Models/Socio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProyectoFinal.Models
{
    public class Socio 
    {
        [Key]
        public int SocioID { get; set; }

        public string Nombre { get; set; }


        public string Apellido { get; set; }


        public string Cedula { get; set; }

        [StringLength(200, ErrorMessage = "El valor minimo es {0}")]
        [DataType(DataType.ImageUrl)]
        public string Foto { get; set; }


        public string Direccion { get; set; }


        [Required]
        public string Telefono { get; set; }

        public string Sexo { get; set; }

        public string Edad { get; set; }
      
       [DataType(DataType.Date)]
        public DateTime FechaNacimiento { get; set; }

        public string Afiliados { get; set; }

        public string Membresia { get; set; }

        public string LugarTrabajo { get; set; }

        public string DireccionOficina { get; set; }

        public string TelefonoOficina { get; set; }

        public string EstadoMembresia { get; set; }

        [DataType(DataType.Date)]
        public DateTime FechaIngreso { get; set; }

        [DataType(DataType.Date)]
        public DateTime FechaSalida { get; set; }

    }
}

ProyectoFinal/Models/SocioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProyectoFinal.Models
{
    public class SocioViewModel
    {
        public int SocioID { get; set; }

        public string Nombre { get; set; }


        public string Apellido { get; set; }


        public string Cedula { get; set; }

  
        public  HttpPostedFileBase Foto { get; set; }

        public string Direccion { get; set; }

        public string Telefono { get; set; }

        public string Sexo { get; set; }

        public string Edad { get; set; }
        [DataType(DataType.Date)]
     
        public DateTime FechaNacimiento { get; set; }

        public string Afiliados { get; set; }

        public string Membresia { get; set; }

        public string LugarTrabajo { get; set; }

        public string DireccionOficina { get; set; }

        public string TelefonoOficina { get; set; }

        public string EstadoMembresia { get; set; }

        [DataType(DataType.Date)]
        public DateTime FechaIngreso { get; set; }

        [DataType(DataType.Date)]
        public DateTime FechaSalida { get; set; }
    }
}

ProyectoFinal/Controllers/SociosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Contex;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    public class SociosController : Controller
    {
        private SotreContext db = new SotreContext();

        // GET: Socios
        public ActionResult Index()
        {
            return View(db.Socios.ToList());
        }

        // GET: Socios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Socio socio = db.Socios.Find(id);
            if (socio == null)
            {
                return HttpNotFound();
            }
            return View(socio);
        }

        // GET: Socios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Socios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SocioViewModel view)
        {
            if (!ModelState.IsValid)
            {
                return HttpNotFound();               
            }
            string path = string.Empty;
            string pic = string.Empty;


            if (view.Foto != null )
            {
                pic = System.IO.Path.GetFileName(view.Foto.FileName);
                path = System.IO.Path.Combine(Server.MapPath("~/Content/Foto"), pic);
                view.Foto.SaveAs(path);
                using (MemoryStream ms = new MemoryStream())
                {
                    view.Foto.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                }
            }

            var socio = new Socio
            {
                Nombre = view.Nombre,
                Apellido = view.Apellido,
                Cedula = view.Cedula,
                Foto = pic == string.Empty ? string.Empty : string.Format("~/Content/Foto/{0}",pic),
                Direccion = view.Direccion,
                Telefono = view.Telefono,
                Sexo = view.Sexo,
                Edad = view.Edad,
                FechaNacimiento = view.FechaNacimiento,
                Afiliados = view.Afiliados,
                Membresia = view.Membresia,
                LugarTrabajo = view.LugarTrabajo,
                DireccionOficina = view.DireccionOficina,
                TelefonoOficina = view.TelefonoOficina,
                EstadoMembresia = view.EstadoMembresia,
                FechaIngreso = view.FechaIngreso,
                FechaSalida = view.FechaSalida
                

            };
            db.Socios.Add(socio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Socios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Socio socio = db.Socios.Find(id);
            if (socio == null)
            {
                return HttpNotFound();
            }
            return View(socio);
        }

        // POST: Socios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SocioID,Nombre,Apellido,Cedula,Foto,Direccion,Telefono,Sexo,Edad,FechaNacimiento,Afiliados,Membresia,LugarTrabajo,DireccionOficina,TelefonoOficina,EstadoMembresia,FechaIngreso,FechaSalida")] Socio socio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(socio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(socio);
        }

        // GET: Socios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Socio socio = db.Socios.Find(id);
            if (socio == null)
            {
                return HttpNotFound();
            }
            return View(socio);
        }

        // POST: Socios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Socio socio = db.Socios.Find(id);
            db.Socios.Remove(socio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/Views/Socios/Create.cshtml
@model ProyectoFinal.Models.Socio

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Socios", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Socio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
              
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
                <span class="btn btn-success">
                    @Html.TextBoxFor(model => model.Foto, new { Type = "File" })
                </span>

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Afiliados, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Afiliados, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Afiliados, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Membresia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Membresia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Membresia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LugarTrabajo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LugarTrabajo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LugarTrabajo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DireccionOficina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DireccionOficina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DireccionOficina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefonoOficina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefonoOficina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefonoOficina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadoMembresia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadoMembresia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadoMembresia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaIngreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaIngreso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaIngreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaSalida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaSalida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaSalida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoFinal/Views/Socios/Delete.cshtml
@model ProyectoFinal.Models.Socio

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Socio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Afiliados)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Afiliados)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Membresia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Membresia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LugarTrabajo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LugarTrabajo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DireccionOficina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DireccionOficina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelefonoOficina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelefonoOficina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoMembresia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoMembresia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaSalida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProyectoFinal/Views/Socios/Details.cshtml
@model ProyectoFinal.Models.Socio

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Socio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Foto))
            {
                <img src="@Url.Content(Model.Foto)" alt="Image" style="height:100px;width:200px;" />
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Afiliados)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Afiliados)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Membresia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Membresia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LugarTrabajo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LugarTrabajo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DireccionOficina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DireccionOficina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelefonoOficina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelefonoOficina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoMembresia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoMembresia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaSalida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SocioID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProyectoFinal/Views/Socios/Index.cshtml
@model IEnumerable<ProyectoFinal.Models.Socio>

@{
    ViewBag.Title = "Index";
}

    <h2 class="text-info">Listado de Socios</h2>

<p>
   
        @Html.ActionLink("Create New", "Create",null, new { @class = "btn btn-primary btn-large" })
   
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cedula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Afiliados)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Membresia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LugarTrabajo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DireccionOficina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TelefonoOficina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstadoMembresia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaSalida)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cedula)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.Foto))
            {
                <img src="@Url.Content(item.Foto)" alt="Image" style="height:50px;width:100px;" />
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sexo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Edad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaNacimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Afiliados)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Membresia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LugarTrabajo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DireccionOficina)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TelefonoOficina)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstadoMembresia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaIngreso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaSalida)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SocioID }, new { @class = "btn btn-info" }) 
            @Html.ActionLink("Details", "Details", new { id=item.SocioID },  new { @class = "btn btn-warning" }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.SocioID }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>